### ISSUE TITLE
Jinja2 include tag is not working for GET j2template API 

### ISSUE THREAD

**Issue by nabapal** [tbotnz/netpalm#19] opened 2020-05-13 04:56 UTC
When I use include tag in j2 templates GET j2template API is not working. However “j2 render  template” API is working fine. Include and extend tag is required to build complex jinja2 templates as per the requirement.

**Comment by tbotnz** [comment] 2020-05-18 04:58
duplicate of #22

**Closed by tbotnz** 2020-05-18 04:58 UTC
